In [ ]:
import numpy as np
# random package is subpackage of numpy

In [ ]:
a=np.arange(1,33).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
a=np.random.rand(8,4) # rand range  is in between 0 and 1
print (a)

[[0.81112368 0.41599754 0.64774037 0.03227977]
 [0.11317616 0.6251232  0.11306779 0.74134216]
 [0.26840163 0.14946988 0.47776841 0.98645272]
 [0.43834447 0.72593354 0.1553403  0.25487204]
 [0.73741528 0.3207097  0.67074327 0.24290195]
 [0.3926063  0.05435167 0.64039656 0.37544942]
 [0.25757326 0.26063041 0.46848475 0.90217396]
 [0.90501469 0.9817854  0.5423372  0.26713039]]


In [ ]:
a=10*np.random.rand(8,4)
print (a)


[[5.51322639 3.47394864 1.78345763 4.65830689]
 [0.11889273 4.90357176 9.03480149 6.7102726 ]
 [7.65801756 0.64955835 9.86689712 6.16433445]
 [3.61331713 3.19917539 7.87188162 7.51918325]
 [0.47730328 1.23905775 2.6173833  4.88541163]
 [9.93418702 4.25270899 1.96073346 4.18707255]
 [5.15217132 1.91784346 8.59146842 7.99314325]
 [8.16517275 5.50492685 1.04164261 6.98415524]]


In [ ]:
np.vsplit(a,4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(a,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(a,(2,5))#split it after 2nd and 5th row

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
a=np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(a,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(a,(2,5))


[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A)

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(A)

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(A)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [ ]:
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
np.cos(A)

array([ 7.07106781e-01,  5.00000000e-01,  6.12323400e-17, -1.00000000e+00])

STATASTICS

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
c=np.arange(1,5).reshape(2,2)

In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.argmax(c)

3

In [ ]:
print(np.argmax(c))

3


In [ ]:
a=10*np.random.rand(6,4)
print(a)

[[6.39671371 4.23865383 5.09574246 9.54829085]
 [2.91175231 0.21825894 7.15163818 9.48849981]
 [6.85786242 1.86602546 5.24288424 1.64421783]
 [8.64425739 8.7360437  6.66863288 3.86664804]
 [9.56217204 2.97642297 6.27944667 0.68767816]
 [8.05446676 5.46327882 1.4227187  3.5416224 ]]


In [ ]:
print(np.argmax(a))

16


In [ ]:
print(np.argmax(a,axis=1))

[3 3 0 1 0 0]


In [ ]:
print(np.argmax(a,axis=0))

[4 3 1 0]


Search

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))



(array([0, 1, 4]),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
b=np.array([2,3,6,14,15,31])
print(np.searchsorted(b,17))


5


In [ ]:
print(np.searchsorted(a,16))
print(a)

5
[ 2  3  6 14 15 31]


In [ ]:
c=[34,6,98,45,6,87]
np.sort(c)

array([ 6,  6, 34, 45, 87, 98])

In [ ]:
s=np.array([True,False,True])
np.sort(s)

array([False,  True,  True])

In [ ]:
s=np.array(['banana','apple','cherry'])
np.sort(s)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

In [ ]:
names=np.array(["sai","ganesh","siva","chinni"])
initials=np.array(["p","q","r","s"])
for i,j in zip(initials,names):
  print(i,".",j)

p . sai
q . ganesh
r . siva
s . chinni


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  441  660  920 1200 1500]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        1.         1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10  0  8 17  2 10]


In [ ]:
a1=np.array([10,21,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 1, 1, 1, 2, 2]), array([10,  0,  8, 17,  2, 10]))


In [ ]:
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))

0.2630344058337938


In [ ]:
a=np.array([10,21,30,40,50,60])
print(np.log10(a))


[1.         1.32221929 1.47712125 1.60205999 1.69897    1.77815125]


In [ ]:
a=np.array([10,21,30,40,50,60])
np.cumprod(a)


array([       10,       210,      6300,    252000,  12600000, 756000000])

In [ ]:
a=np.array([10,21,30,40,50,60])
np.diff(a)

array([11,  9, 10, 10, 10])

In [ ]:
a=34
b=17
np.lcm(a,b)


34

In [ ]:
np.gcd(a,b)

17

In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)
print(gc)

3


In [ ]:
a=np.array([12,15,60])
gc=np.lcm.reduce(a)
print(gc)